repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.8.5
    hooks:
      - id: gitleaks
        args: ["--config", ".github/config/.gitleaks.toml", "--verbose"]
